# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 675)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_one_load_image = QtWidgets.QPushButton(self.groupBox)
        self.btn_one_load_image.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_one_load_image.setObjectName("btn_one_load_image")
        self.verticalLayout.addWidget(self.btn_one_load_image)
        self.label_one_image = QtWidgets.QLabel(self.groupBox)
        self.label_one_image.setMinimumSize(QtCore.QSize(0, 0))
        self.label_one_image.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_one_image.setObjectName("label_one_image")
        self.verticalLayout.addWidget(self.label_one_image)
        self.btn_color_separation = QtWidgets.QPushButton(self.groupBox)
        self.btn_color_separation.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_color_separation.setObjectName("btn_color_separation")
        self.verticalLayout.addWidget(self.btn_color_separation)
        self.btn_color_transformation = QtWidgets.QPushButton(self.groupBox)
        self.btn_color_transformation.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_color_transformation.setObjectName("btn_color_transformation")
        self.verticalLayout.addWidget(self.btn_color_transformation)
        self.btn_color_extraction = QtWidgets.QPushButton(self.groupBox)
        self.btn_color_extraction.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_color_extraction.setObjectName("btn_color_extraction")
        self.verticalLayout.addWidget(self.btn_color_extraction)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout.addWidget(self.groupBox_5, 0, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout.addWidget(self.groupBox_4, 0, 3, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout.addWidget(self.groupBox_3, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "F74121246_HW1"))
        self.groupBox.setTitle(_translate("MainWindow", "1. Image Processing"))
        self.btn_one_load_image.setText(_translate("MainWindow", "Load Image"))
        self.label_one_image.setText(_translate("MainWindow", "TextLabel"))
        self.btn_color_separation.setText(_translate("MainWindow", "1.1 Color Separation"))
        self.btn_color_transformation.setText(_translate("MainWindow", "1.2 Color Transformation"))
        self.btn_color_extraction.setText(_translate("MainWindow", "1.3 Color Extraction"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2. Image Smoothing"))
        self.groupBox_5.setTitle(_translate("MainWindow", "5. Adaptive Threshold"))
        self.groupBox_4.setTitle(_translate("MainWindow", "4. Transforms"))
        self.groupBox_3.setTitle(_translate("MainWindow", "3. Edge Detection"))
